# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capone}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Denis Barushev"]
  s.date = %q{2009-12-09}
  s.email = %q{barushev@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "lib/capone.rb",
     "recipes/daemon_strategies/mongrel_cluster.rb",
     "recipes/daemon_strategies/passenger.rb",
     "recipes/daemon_strategy.rb",
     "recipes/db.rb",
     "recipes/defaults.rb",
     "recipes/delayed_job.rb",
     "recipes/gems.rb",
     "recipes/nginx.rb",
     "recipes/whenever.rb"
  ]
  s.homepage = %q{http://github.com/denis/capone}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Capone is the set of rake tasks and capistrano recipes.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.5.0"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.5.0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.5.0"])
  end
end

